// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/nexus/nexus.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	config "github.com/skatteetaten/architect/v2/pkg/config"
	nexus "github.com/skatteetaten/architect/v2/pkg/nexus"
)

// MockDownloader is a mock of Downloader interface.
type MockDownloader struct {
	ctrl     *gomock.Controller
	recorder *MockDownloaderMockRecorder
}

// MockDownloaderMockRecorder is the mock recorder for MockDownloader.
type MockDownloaderMockRecorder struct {
	mock *MockDownloader
}

// NewMockDownloader creates a new mock instance.
func NewMockDownloader(ctrl *gomock.Controller) *MockDownloader {
	mock := &MockDownloader{ctrl: ctrl}
	mock.recorder = &MockDownloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloader) EXPECT() *MockDownloaderMockRecorder {
	return m.recorder
}

// DownloadArtifact mocks base method.
func (m *MockDownloader) DownloadArtifact(c *config.MavenGav) (nexus.Deliverable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadArtifact", c)
	ret0, _ := ret[0].(nexus.Deliverable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadArtifact indicates an expected call of DownloadArtifact.
func (mr *MockDownloaderMockRecorder) DownloadArtifact(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadArtifact", reflect.TypeOf((*MockDownloader)(nil).DownloadArtifact), c)
}
