// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/trace/trace.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	config "github.com/skatteetaten/architect/v2/pkg/config"
	runtime "github.com/skatteetaten/architect/v2/pkg/config/runtime"
	docker "github.com/skatteetaten/architect/v2/pkg/docker"
	trace "github.com/skatteetaten/architect/v2/pkg/trace"
)

// MockTrace is a mock of Trace interface.
type MockTrace struct {
	ctrl     *gomock.Controller
	recorder *MockTraceMockRecorder
}

// MockTraceMockRecorder is the mock recorder for MockTrace.
type MockTraceMockRecorder struct {
	mock *MockTrace
}

// NewMockTrace creates a new mock instance.
func NewMockTrace(ctrl *gomock.Controller) *MockTrace {
	mock := &MockTrace{ctrl: ctrl}
	mock.recorder = &MockTraceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrace) EXPECT() *MockTraceMockRecorder {
	return m.recorder
}

// ScanImage mocks base method.
func (m *MockTrace) ScanImage(buildFolder string) ([]trace.Dependency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanImage", buildFolder)
	ret0, _ := ret[0].([]trace.Dependency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanImage indicates an expected call of ScanImage.
func (mr *MockTraceMockRecorder) ScanImage(buildFolder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanImage", reflect.TypeOf((*MockTrace)(nil).ScanImage), buildFolder)
}

// SendBaseImageMetadata mocks base method.
func (m *MockTrace) SendBaseImageMetadata(application config.ApplicationSpec, imageInfo *runtime.ImageInfo, containerConfig *docker.ContainerConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendBaseImageMetadata", application, imageInfo, containerConfig)
}

// SendBaseImageMetadata indicates an expected call of SendBaseImageMetadata.
func (mr *MockTraceMockRecorder) SendBaseImageMetadata(application, imageInfo, containerConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBaseImageMetadata", reflect.TypeOf((*MockTrace)(nil).SendBaseImageMetadata), application, imageInfo, containerConfig)
}

// SendImageMetadata mocks base method.
func (m *MockTrace) SendImageMetadata(data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendImageMetadata", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendImageMetadata indicates an expected call of SendImageMetadata.
func (mr *MockTraceMockRecorder) SendImageMetadata(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendImageMetadata", reflect.TypeOf((*MockTrace)(nil).SendImageMetadata), data)
}
